name: Build & Deploy Quartz to GitHub Pages

on:
  push:
    branches: [ main ]

env:
  THEME_NAME: default

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch Quartz Theme
        run: curl -s -S https://raw.githubusercontent.com/saberzero1/quartz-themes/master/action_v1.sh | bash -s -- $THEME_NAME

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build Quartz
        uses: konstfish/quartz-build-action@v7
        with:
          source: content
          page_title: "🔭"
          page_base_url: "sleepywndud.github.io"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4